# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo:4.4.6
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    ports:
      - 27017:27017 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: zips
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: 'mongodb://root:example@mongo:27017/zips?authSource=admin'
